### ISSUE TITLE
Validation Update Checklist

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/Accelerated-Mobile-Pages#153]
- [x]  https://goo.gl/bvuckS
  - The attribute 'value' in tag 'li' is set to the invalid value 'embrace'.
  - The attribute 'value' in tag 'li' is set to the invalid value 'health'.
  - The attribute 'value' in tag 'li' is set to the invalid value 'nation'.
  - The attribute 'value' in tag 'li' is set to the invalid value 'pets'.
  - The attribute 'value' in tag 'li' is set to the invalid value 'plan'.
  - The attribute 'value' in tag 'li' is set to the invalid value 'prenium'.
- [x]  Updating Page Exclude option at https://goo.gl/oyvbQo 
- [x]  https://goo.gl/vJ8qEp
  - The attribute 'contenteditable' may not appear in tag 'a'.
- [x]  https://goo.gl/xp0Cte
  - The attribute 'type' may not appear in tag 'ul'.
- [x] https://goo.gl/ukHT4W
  - The attribute 'width' may not appear in tag 'col'.
- [x]  https://goo.gl/bMSQOo
  - The attribute 'height' may not appear in tag 'table'.
- [ ]  https://goo.gl/sNKapJ
  - The attribute 'nowrap' may not appear in tag 'td'.
- [x]  https://goo.gl/ykn8JP
  - Structured data: Important: Default image if there is no featured image: A value for the image field is required. 
- [ ]  https://goo.gl/ZejPsQ
  - The attribute 'width' in tag 'amp-iframe' is set to the invalid value ''.
- [x] V: time="" non-refundable="" security="" deposit="" for=“” ( https://goo.gl/4ZP1js )
- [x]  Nextgen problem The offending items include:
  <!– ngg_resource_manager_marker –><!– ngg_resource_manager_marker –>
  and
  jquery-migrate.min.js (which creates a dependency for jquery too)
- [ ]  This came in email from Jon
  ![screen shot 2016-10-13 at 10 41 53 am](https://cloud.githubusercontent.com/assets/16532359/19407416/4b610226-92bf-11e6-9de0-9420492c51aa.png)
  ![screen shot 2016-10-13 at 10 41 57 am](https://cloud.githubusercontent.com/assets/16532359/19407417/4d2b9152-92bf-11e6-9b54-6a38be317868.png)
- [ ] https://goo.gl/W8aZsE
  - The attribute 'scoped' may not appear in tag 'style amp-custom'.
  - The parent tag of tag 'style amp-custom' is 'div', but it can only be 'head'.
  - The attribute 'scoped' may not appear in tag 'style amp-custom'.
  - The parent tag of tag 'style amp-custom' is 'div', but it can only be 'head'.

**Comment by MohammedKaludi** [comment]
Structured data issue fixed in Commit e63083c

**Comment by ahmedkaludi** [comment]
The Jon's error is a global issue, we are working on it. For now, I am closing this. This is issue will be resumed in https://github.com/ahmedkaludi/Accelerated-Mobile-Pages/issues/169
