### ISSUE TITLE
Need to create a tutorial on Advanced Analytics Tracking Event Options and with a proper link to that near that option

### ISSUE THREAD

**Issue by Zabi09** [ahmedkaludi/accelerated-mobile-pages#1630]
Need to create a tutorial on Advanced Analytics Tracking Event Options and with a proper link to that near that option

See this screenshot: http://take.ms/I364T

Ref: https://secure.helpscout.net/conversation/509026534/20508?folderId=1060551

**Comment by MARQAS** [comment]
- [ ] Tutorial

- [ ] Add link to the options panel

- [ ] Rename the options

- [ ] Add the default code

**Comment by MARQAS** [comment]
#1860

**Comment by MARQAS** [comment]
https://ampforwp.com/tutorials/article/add-advanced-google-analytics-amp/

**Comment by MohammedKaludi** [comment]
:+1:
