### ISSUE TITLE
Divide the options into sections

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#1823]
- [x] Divide the options into sections

- [x] Fix this issues as well: http://take.ms/1SeCw

- [x] First time loading issue in section

- [ ] Search Icon 

- [x] Label fix

- [x] Restructure options

- [x] Settings link

- [x] Small Options design 

- [ ] Dashboard improve

**Comment by ahmedkaludi** [comment]
## Tasks:

- [ ] 1. Section name jumps: http://take.ms/azhJa

**Comment by ahmedkaludi** [comment]
done
