### ISSUE TITLE
0.9 Development Testing

### ISSUE THREAD

**Issue by daanishd** [ahmedkaludi/accelerated-mobile-pages#2125]
Ref: http://take.ms/XdcDI7

No idea why these warnings are displayed. It shouldn't come.

**Comment by MohammedKaludi** [comment]
- [ ] Single Classes are loading on Homepage in Design #3 http://take.ms/sQk40

**Comment by MARQAS** [comment]
- [ ] Widgets

- [ ] GDPR

**Comment by ahmedkaludi** [comment]
- [ ] Errors on Category pages: http://take.ms/wD7qZ

**Comment by Zabi09** [comment]
- [ ] AD #1 is not working on homepage being SiteWide

- [ ] AD #2 - Need to rename below the Footer (SiteWide) to above the Footer SiteWide and it's not working on the homepage too

**Comment by ahmedkaludi** [comment]
- [ ] <meta name="generator" content="AMP Plugin v0.7.0" />: http://take.ms/XjQDZ - It should instead say: AMPforWP  

- [ ] in 0.9-dev branch, I have a validation issue on the homepage: The extension 'amp-playbuzz' was found on this page, but is unused. + All the scripts are loading on the output.

**Comment by ahmedkaludi** [comment]
Our .css and .js files should have the current version number on it.

- [ ] includes/options/redux-core/assets/css/redux-admin.css

- [ ] includes/options/redux-core/assets/css/vendor/elusive-icons/elusive-icons.css?ver=3.6.2.1526636347

- [ ] includes/options/extensions/theme_design_selector/theme_design_selector/field_theme_design_selector.css?ver=1

- [ ] /includes/options/extensions/demolink_image_select/demolink_image_select/field_demolink_image_select.css?ver=1526636347

- [ ]  and all the others: http://take.ms/fSEt8
