### ISSUE TITLE
Issues in Beta Version 0.9.98

### ISSUE THREAD

**Issue by merajali294** [ahmedkaludi/accelerated-mobile-pages#2332]
- [x] 1. Potential issues after installing the Beta Version at user's end, tested by Me and Ahmed Sir.

 Ex 1 : Ampforwp_Walker_Nav_Menu->

Example Video: https://monosnap.com/file/rpKmuYU1YUCHoXcxsXIWBogtODNBFV

**Comment by ahmedkaludi** [comment]
- [ ] 2. Warning: in_array() expects parameter 2 to be array,
see this screenshot:  http://monosnap.com/image/1HnrVdOMTwOWXjqhBQMoN8FNwAbZV4/

Ref:  https://secure.helpscout.net/conversation/614426939/29439?folderId=1914712

solution:  `if ( is_array( $metadata ) ) {
				if( in_array( "image" , $metadata ) ) {
					if ( $metadata['image']['width'] < 696 ) {
			 			$metadata['image']['width'] = 700 ;
		     		}
				}
			}`
- [ ] 5. Warning: in_array() expects parameter 2 to be array,
see this screenshot:  http://monosnap.com/image/1HnrVdOMTwOWXjqhBQMoN8FNwAbZV4/

Ref:  https://secure.helpscout.net/conversation/614426939/29439?folderId=1914712

solution:  `if ( is_array( $metadata ) ) {
				if( in_array( "image" , $metadata ) ) {
					if ( $metadata['image']['width'] < 696 ) {
			 			$metadata['image']['width'] = 700 ;
		     		}
				}
			}`

**Comment by RajuJeelaga** [comment]
4. 0.9.98 Branch, it breaks the Previous Swift Default Layout, like Landing page and Pricing Page, See the Screenshot.

### Landing page
- [ ] https://monosnap.com/file/Fgo24z7oE6QhS4ubbL8vgzqkewexEN

### Pricing page
- [ ] https://monosnap.com/file/LNdp1A2u3JVey4CJV8PpvndjS2JPuM

- [ ] It makes problem in 0.9.98 and 0.9.96, It's working fine in 0.9.97.3 branch.

**Comment by RajuJeelaga** [comment]
### Task List

- [ ] Check All the Layouts With .98 Beta Version. (This layout Makes Problem https://ampforwp.com/demo/layout-2/amp/)

- [ ] Icons are not Loading https://monosnap.com/file/WD3bSdoF5DR5wMUuUVtaWpj8mxJIU3

- [ ] Pagebuilder Panel is showing Empty https://monosnap.com/file/e2Drvr0l20VlqwR9gaU8FMd81St8CE

**Comment by Zabi09** [comment]
- [ ] Do we need this function now - http://take.ms/502kY ?

**Comment by syedimran22** [comment]
Description: Plugin Manager is reflecting two times in AMP setting.

Ref: https://secure.helpscout.net/conversation/623328482/30520?folderId=1060556

Screenshot: http://take.ms/bck7r

**Comment by Zabi09** [comment]
- [ ] AMPforWP styles and js are also loading in other themes/plugins which users the redux framework like Herald.
See this screenshots:
http://take.ms/3GVmz
http://take.ms/a6Ghq

**Comment by MARQAS** [comment]
`Q: Description: Plugin Manager is reflecting two times in AMP setting`
It was in plugin manager plugin, it was removing the section in `after_setup_theme` hook. made a change in that, it will now be resolved.

**Comment by MARQAS** [comment]
- [ ] calling of WP_Filesystem_Direct in redux-core. 

- [ ] Check calling of other classes as well

**Comment by Zabi09** [comment]
Gallery shortcode is not rendering the images in beta and that is because of this filter - http://take.ms/BKhyl

Added in: https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/a729c3c719c3bfe99f9c5e31c7f167364382679a

**Comment by MohammedKaludi** [comment]
@MARQAS and @Zabi09 
Regarding: https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/2332#issuecomment-406588288

Yes remove it, also need to check and remove this_screen_own() and its script if it is not using.

**Comment by ahmedkaludi** [comment]
- [ ] http://take.ms/OV66i - why does this not work in Design 3?

**Comment by syedimran22** [comment]
Desc: Bruno is getting more Amp errors in the error log and also the single pages/post are not reflecting.
[Uploading after new beta error log.txt…]()

Error logs : #0 /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-style-sanitizer.php(189): AMPforWP\AMPVendor\AMP_Style_Sanitizer->process_style_element(Object(DOMElement))
#1 /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(124): AMPforWP\AMPVendor\AMP_Style_Sanitizer->sanitize()
#2 /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/ve in /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-style-sanitizer.php on line 286
[17-Sep-2018 12:57:05 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/features/advertisement/ads-options.php:1) in /home/showmete/public_html/wp-admin/includes/misc.php on line 1126
[17-Sep-2018 12:57:05 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to AMPforWP\AMPVendor\AMP_Style_Sanitizer::process_style_element() must be an instance of AMPforWP\AMPVendor\DOMElement, instance of DOMElement given, called in /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-style-sanitizer.php on line 189 and defined in /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-style-sanitizer.php:286
Stack trace:
#0 /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-style-sanitizer.php(189): AMPforWP\AMPVendor\AMP_Style_Sanitizer->process_style_element(Object(DOMElement))
#1 /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/class-amp-content.php(124): AMPforWP\AMPVendor\AMP_Style_Sanitizer->sanitize()
#2 /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/ve in /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-style-sanitizer.php on line 286
[17-Sep-2018 12:57:08 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/features/advertisement/ads-options.php:1) in /home/showmete/public_html/wp-admin/includes/misc.php on line 1126
[17-Sep-2018 12:57:09 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/features/advertisement/ads-options.php:1) in /home/showmete/public_html/wp-admin/includes/misc.php on line 1126
[17-Sep-2018 12:57:12 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/features/advertisement/ads-options.php:1) in /home/showmete/public_html/wp-admin/includes/misc.php on line 1126
[17-Sep-2018 12:57:14 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/features/advertisement/ads-options.php:1) in /home/showmete/public_html/wp-admin/includes/misc.php on line 1126
[17-Sep-2018 12:57:17 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/features/advertisement/ads-options.php:1) in /home/showmete/public_html/wp-admin/includes/misc.php on line 1126
[17-Sep-2018 12:57:18 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to AMPforWP\AMPVendor\AMP_Style_Sanitizer::process_style_element() must be an instance of AMPforWP\AMPVendor\DOMElement, instance of DOMElement given, called in /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-style-sanitizer.php on line 189 and defined in /home/showmete/public_html/wp-content/plugins/accelerated-mobile-pages/includes/vendor/amp/includes/sanitizers/class-amp-style-sanitizer.php:286

Ref: https://secure.helpscout.net/conversation/660702283/33925?folderId=2169248

**Comment by MARQAS** [comment]
- [ ] Show/Hide of Pages/Posts from Hide AMP bulk Tools not working

**Comment by MARQAS** [comment]
There are some issues with AMP layouts which I have created a ticket in AMP layouts and it is not related to beta, those issues are valid with Master as well

**Comment by MARQAS** [comment]
And also if there are any more issues related to beta then please create a new ticket, this ticket is getting bigger and bigger.

**Comment by MohammedKaludi** [comment]
Contact me before migrating the code

**Comment by ahmedkaludi** [comment]
No More new commits in this ticket please.

**Comment by MARQAS** [comment]
All the issues in 0.9.98 have been resolved, And Our new beta version is 0.9.99 if anyone faces any issue in it, please create a new ticket.
Closing this ticket.
