### ISSUE TITLE
Design 3 Checklist

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#494]
- [x] Responsive Version - (Ahmed)

- [x] Search https.... 
- [x] Default installation on fresh wp
- [x] AD positions
- [x] Styling of discus comments  - (Ahmed)

- [x] Single Element Position Defaults in Design Manager - (Review from Ahmed)

- [x] Check the canonical and amphtml tags (In/Out) - (Khaled)

- [x] Design color picker

- [x] Logo image uploader 

- [x] Code check and review of style.php - (Mohammed)

- [x] Search form in header - (Mohammed)

- [x] Carousel Connect with Options - (Mohammed)

- [x] Localization of the texts - (Khaled)

- [x] Options panel for Design 3 - (Khaled)

- [x] Clickable labels of Tags and categories - (Khaled)

- [x] Social Icons in footer and drawer menu - (Khaled)

- [x] Pagination Text Defaults - (Khaled)

- [x]  in design 3 search - when searched for something rel="canonical" is wrong
AND for the same above issue rel="amphtml" is wrong on search page in non amp version - (Khaled)

**Comment by ahmedkaludi** [comment]
Search is built, needs crafting https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/dbd08cad03cef900f8a4e1ac4a40bea4e1d1c1ce

**Comment by khaledMohammed000** [comment]
21. archive.php not present in design 3
22. proper links for mibile redirection everywhere check ? header, footer
23. check this CSS issue http://take.ms/T1YO8 in design -1-3 all footers
24. review by mohammed bhai preg_replace code for link in footer in design 1-2
25. non amp link was not even present in design 1 in pages, also check in design 3
26. home page and archive support off(make categories and tags clickable onsinglein design 3) rahe toh links logo mein se non amp ke hojana

28. disqus comments on deign3
29. archives absolutely not working in design 3
	http://localhost/amp/wordpress/uncategorized/how-to-change-text-on-navigation-links/amp/

**Comment by khaledMohammed000** [comment]
29. in design 3 search - when searched for something rel="canonical" is wrong
30. for the same above issue rel="amphtml" is wrong on search page in non amp version

**Comment by riyaz95** [comment]
improper tags alignment in Design 3 

![tags](https://cloud.githubusercontent.com/assets/15712354/23822800/392efd54-067a-11e7-9422-e8ca3165cac1.png)

**Comment by ahmedkaludi** [comment]
we are closing this to stay focused
