### ISSUE TITLE
Checklist 0.9.46 Update

### ISSUE THREAD

**Issue by khaledMohammed000** [ahmedkaludi/accelerated-mobile-pages#743]
- [ ] add conditions for require for AMPplugin at the start of file
- [ ] conditional code for different designs
- [x] add scripts standard way
- [ ] rename all functions
- [ ] plain permalinks andour plugin not working
- [ ] stripping function revamp
- [ ] check all places custom editor is working or not ?
- [x] features.php need more 2 iterations for saperating types of functions 
- [x] 650 Line se phir karo features.php
- [x] is_front_page() is connected reading setting in wp-admin replace it with redux_amp variable
- [ ] Settings link from plugin page gone after code is moved
- [ ] add comments explaining what each fileis for ( Recommended by Ahmed Bhai)
- [ ] Merge all the scripts function into a single function likewise for Structured data functions
- [ ] review TODO in templates\features\general\structured-data.php
- [ ] review compatibility with all expetnsions
- [ ] Check if all the code in compatibility.php is working as expected or not
- [ ] remove footer file return code from file.php once merge of designs is done
- [ ] links in widgets out are not /amp/ but are /amp
- [ ] Make sure patches of 0.9.45.X are added into 0.9.46 and are tested
- [ ] Make sure all Debug issue are removed

**Comment by ahmedkaludi** [comment]
0.9.46 was skipped
